version: '3.7'

services:
  goosepond:
    image: lymmers/lymmers.com:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lymmers
    restart: always
    ports:
      - 8008:8008
    env_file:
      - .env
    volumes:
      - ./apps/:/apps/
      - ./project/:/project/
